# Generated by Django 5.1.1 on 2025-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('User', 'User')], max_length=50),
        ),
    ]
